Frontend authentication
vajgi90/StockMarket-Angular-Springboot pull request #4
Opened 2020-01-29 19:10 UTC by vajgi90

- User Login 
- Menu Elements(guarded)
- User Registration
- Autologin/Autologout
- AuthGuard

2020-02-03 23:13 UTC, borosr requested changes

2020-02-03 23:13 UTC, borosr commented on stockmarket/src/app/app.component.ts
> +    this.userSub = this.authService.token.subscribe(token => {
ha már eltárolod, akkor unsubscribe-olj róla OnDestroykor.

2020-02-03 23:13 UTC, borosr commented on stockmarket/src/app/login/login.component.html
> +          id="email"
Legyen egységes a formázás. Mindegy melyik mellett döntesz, csak egy legyen. Vagy attribútumonként tördelj vagy legyen inline.

2020-02-03 23:13 UTC, borosr commented on stockmarket/src/app/service/auth.service.ts
> +      'http://localhost:8080/oauth/token',
ez legyen konstansban

2020-02-03 23:13 UTC, borosr commented on stockmarket/src/app/service/auth.service.ts
> +/*     const loadedData = new AuthToken(
ne legyenek commentezett részek

2020-02-03 23:13 UTC, borosr commented on stockmarket/src/app/stockdata/stockdata.component.ts
> +    this.stockService.getAllStockMonthlyBySymbol('TSLA').subscribe(data => {
Ezek mehetnének egy `forkJoin`-al egyszerre

2020-02-04 15:03 UTC, vajgi90 commented on stockmarket/src/app/app.component.ts
> +    this.userSub = this.authService.token.subscribe(token => {
Javítva.

2020-02-04 15:07 UTC, vajgi90 commented on stockmarket/src/app/login/login.component.html
> +          id="email"
Javítva!

2020-02-04 15:11 UTC, vajgi90 commented on stockmarket/src/app/service/auth.service.ts
> +      'http://localhost:8080/oauth/token',
Javítva.

2020-02-04 15:12 UTC, vajgi90 commented on stockmarket/src/app/stockdata/stockdata.component.ts
> +    this.stockService.getAllStockMonthlyBySymbol('TSLA').subscribe(data => {
Javítva!

2020-02-05 20:30 UTC, borosr approved these changes

2020-02-24 17:05 UTC, merged